# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set tmux color to 256
if [ "$TERM" != "xterm-256color" ]; then
  export TERM=xterm-256color
fi

# Set zsh theme
ZSH_THEME="mytheme"

# Set the command execution time stamp shown in the history command output
HIST_STAMPS="mm/dd/yyyy"

# Custom plugins
plugins=(git)

# oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Alias
alias g="git"
